export default {
    CREATE_LANE: 'CREATE_LANE',
    UPDATE_LANE: 'UPDATE_LANE',
    DELETE_LANE: 'DELETE_LANE',
    ATTACH_NOTE: 'ATTACH_NOTE',
    DETACH_NOTE: 'DETACH_NOTE',
    MOVE_NOTE:   'MOVE_NOTE',

    CREATE_NOTE: 'CREATE_NOTE',
    UPDATE_NOTE: 'UPDATE_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
}
